name: CI

on:
  push:
    branches-ignore: [dev]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    name: CI (Java ${{ matrix.java }})
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -T 1C -B package -Pbuild-extras --file pom.xml
      env:
        JAVA_TOOL_OPTIONS: -Xmx2G
